# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bezichtiging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam_bezoeker', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')], verbose_name='Voornaam')),
                ('achternaam_bezoeker', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')], verbose_name='Achternaam')),
            ],
            options={
                'verbose_name_plural': 'Bezichtigingen',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')])),
            ],
            options={
                'verbose_name_plural': "Criteria's",
            },
        ),
        migrations.CreateModel(
            name='Eigenschap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')])),
                ('oppervlakte', models.CharField(blank=True, default='0', max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Enkel alphanumerische waarden toegtelaten bv. abc123  .')])),
                ('eenheid', models.CharField(blank=True, default='M', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Eigenschappen',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field')),
                ('height_field', models.IntegerField(default=0, verbose_name='height')),
                ('width_field', models.IntegerField(default=0, verbose_name='width')),
            ],
            options={
                'verbose_name_plural': "Pand foto's",
            },
        ),
        migrations.CreateModel(
            name='Pand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straat_naam', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')])),
                ('huis_nummer', models.IntegerField()),
                ('stad', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')])),
                ('postcode', models.IntegerField()),
                ('prijs', models.DecimalField(decimal_places=2, max_digits=16)),
                ('beschrijving', models.TextField()),
                ('hits', models.IntegerField(default=0)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Fase')),
            ],
            options={
                'ordering': ['user'],
                'verbose_name_plural': 'Pand',
            },
        ),
        migrations.CreateModel(
            name='PandBezichtiging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('bezichtiging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Bezichtiging')),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pand')),
            ],
            options={
                'verbose_name_plural': 'Pand bezichtigingen',
            },
        ),
        migrations.CreateModel(
            name='PandCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal', models.SmallIntegerField(default=1)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Criteria')),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pand')),
            ],
            options={
                'verbose_name_plural': "Pand criteria's",
            },
        ),
        migrations.CreateModel(
            name='PandEigenschap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eigenschap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Eigenschap')),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pand')),
            ],
            options={
                'verbose_name_plural': 'Pand eigenschappen',
            },
        ),
        migrations.CreateModel(
            name='PandReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pand')),
            ],
            options={
                'verbose_name_plural': 'Pand reviews',
            },
        ),
        migrations.CreateModel(
            name='PandVerbruiksType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pand')),
            ],
            options={
                'verbose_name_plural': 'Pand verbruikstypen',
            },
        ),
        migrations.CreateModel(
            name='PandWettelijk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppervlakte', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[0-9]+(\\.[0-9]{1,5})?$', 'Enkel decimalen toegelaten bv. 0.1')])),
                ('eenheid', models.CharField(blank=True, default='M', max_length=10)),
                ('jaartal', models.DateField()),
                ('pand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pand')),
            ],
            options={
                'verbose_name_plural': 'Wettelijke informaties van panden',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_naam', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')], verbose_name='Auteur')),
                ('review_text', models.TextField(verbose_name='review')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=65, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')])),
            ],
            options={
                'verbose_name_plural': 'Statussen',
            },
        ),
        migrations.CreateModel(
            name='Supportticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('beschrijving', models.TextField()),
                ('datum', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Supporttickets',
            },
        ),
        migrations.CreateModel(
            name='TypeHuis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=65, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')])),
            ],
            options={
                'verbose_name_plural': 'Type huizen',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('locatie', models.CharField(blank=True, max_length=140)),
                ('geslacht', models.CharField(blank=True, choices=[('a', 'Man'), ('b', 'Vrouw'), ('c', 'Anders')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VerbruiksType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')])),
            ],
            options={
                'verbose_name_plural': 'Verbruikstypen',
            },
        ),
        migrations.CreateModel(
            name='Wettelijk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z_ ]*$', 'Enkel letters toegelaten bv a-z,A-Z')])),
            ],
            options={
                'verbose_name': 'wettelijke informatie',
                'verbose_name_plural': 'Wettelijke informaties',
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pandwettelijk',
            name='wettelijk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Wettelijk', verbose_name='wettelijke informatie'),
        ),
        migrations.AddField(
            model_name='pandverbruikstype',
            name='verbruik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.VerbruiksType'),
        ),
        migrations.AddField(
            model_name='pandreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Review'),
        ),
        migrations.AddField(
            model_name='pand',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Status'),
        ),
        migrations.AddField(
            model_name='pand',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.TypeHuis'),
        ),
        migrations.AddField(
            model_name='pand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto',
            name='pand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pand'),
        ),
        migrations.AlterUniqueTogether(
            name='pandcriteria',
            unique_together=set([('pand', 'criteria')]),
        ),
        migrations.AlterUniqueTogether(
            name='pandbezichtiging',
            unique_together=set([('pand', 'bezichtiging', 'datum')]),
        ),
    ]
