# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_gallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='foto',
        ),
    ]
