# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_foto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='foto',
            field=models.FileField(default='', upload_to=b''),
        ),
    ]
