# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.FileField(upload_to='images/', verbose_name='File'),
        ),
    ]
