# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20160503_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.AddField(
            model_name='image',
            name='pand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='master.Pand'),
        ),
    ]
