# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20160503_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AddField(
            model_name='pand',
            name='profiel_foto',
            field=models.FileField(default='', upload_to='media/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='media/', verbose_name='File'),
        ),
    ]
