# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20160504_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pand',
            name='profiel_foto',
            field=models.FileField(default='', upload_to='media/', verbose_name='Profiel_foto'),
        ),
    ]
