# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20160509_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(default=datetime.datetime(2016, 5, 10, 11, 8, 47, 713000, tzinfo=utc), upload_to='media/', verbose_name='File'),
            preserve_default=False,
        ),
    ]
